---
- name: Populate service facts
  service_facts:

- name: Get liagentd status
  debug:
    msg: "Log Insight agent is {{ ansible_facts.services['liagentd.service'].state }}"
  register: liagentstatus
  ignore_errors: yes

- name: Agent check.
  debug:
    msg: "vRLI agent is already installed so skipping installation."
  when: liagentstatus is success

- name: Begin vRLI agent install.
  block:
  - name: vRLI agent install.
    debug:
      msg: "vRLI agent will now be installed."

  - name: Downloading vRLI agent locally
    command: curl -k -o /tmp/liagent.deb "{{ liserver_uri }}"

  - name: Install package
    apt:
      deb: /tmp/liagent.deb
      state: present
    register: installed

  - name: Set hostname
    ini_file:
      path: /var/lib/loginsight-agent/liagent.ini
      section: server
      option: hostname
      value: "{{ liserver }}"
      create: no
      state: present
      no_extra_spaces: yes

  - name: Set protocol
    ini_file:
      path: /var/lib/loginsight-agent/liagent.ini
      section: server
      option: proto
      value: "{{ liproto }}"
      create: no
      state: present
      no_extra_spaces: yes

  - name: Set port
    ini_file:
      path: /var/lib/loginsight-agent/liagent.ini
      section: server
      option: port
      value: "{{ liport }}"
      create: no
      state: present
      no_extra_spaces: yes

  - name: Set SSL option
    ini_file:
      path: /var/lib/loginsight-agent/liagent.ini
      section: server
      option: ssl
      value: "{{ lissl }}"
      create: no
      state: present
      no_extra_spaces: yes

  - name: Set automatic updates
    ini_file:
      path: /var/lib/loginsight-agent/liagent.ini
      section: update
      option: auto_update
      value: "{{ liauto_update }}"
      create: no
      state: present
      no_extra_spaces: yes

  - name: Remove temporary file
    file:
      path: /tmp/liagent.deb
      state: absent
  when:
    - liagentstatus is failed